### ISSUE TITLE
Style the Login/Signup components & Change the routing

### ISSUE THREAD

**Issue by Shiro-Raven** [Logician724/T10-Sprint1#10]
Nesrin suggested that the routing should be done in the dashboard module instead of the app module.

**Comment by reda-i** [comment]
You should have said so in the beginning. Also, what is the advantage?

**Comment by Shiro-Raven** [comment]
It's just a suggestion by Nesrin. If you think it's not aesthetic please say so.

**Comment by reda-i** [comment]
Well, logically speaking, authentication has nothing to do with the dashboard. They are completely separate modules. Speaking of aesthetics, a better approach is to put authentication components in their own module. and call them from the app router just like the dashboard.

**Comment by reda-i** [comment]
Shall I work with that, or what do you think? @Shiro-Raven @NesrinAbdulaziz
